### ISSUE TITLE
Raise Occultists: Max button not always working properly

### ISSUE THREAD

**Issue by ko-pp** [agateblue/demonology#11]
See screenshot, I should be able to use the  "Max" button to buy one (1) Occultist:

![Screenshot-2022-05-24T14-04-53+0200](https://user-images.githubusercontent.com/2778040/170030932-211ed794-3df6-474d-91a8-21d207b906d7.png)

A single extra Minion unblock the button

![Screenshot-2022-05-24T14-13-49+0200](https://user-images.githubusercontent.com/2778040/170032040-a20951a6-399c-4537-9e9d-898c51e2830f.png)

Edit: it seems that the "Auto buy" function doesn’t work when the "Max" button is disabled (no screenshot on this one, sorry)

**Comment by agateblue** [comment]
Thanks, let me try to reproduce that!

**Comment by agateblue** [comment]
So the issue is with [this function](https://github.com/agateblue/demonology/blob/main/src/game.js#L62-L74)

```javascript
export function getGeometricMaxBuyable ({start, available, base, increaseFactor}) {
  // from https://blog.kongregate.com/the-math-of-idle-games-part-i/
  let basePrice = base
  let expo = increaseFactor
  let unitsOwned = start
  let topHalf = available * (expo - 1)
  let bottomHalf = (expo ** unitsOwned) * basePrice
  let step = topHalf / bottomHalf + 1
  let logged = Math.log(step) / Math.log(expo)
  let maxBuys = Math.floor(logged)

  return maxBuys
}
```

Given a unit start price, increase factor, current quantity and available currency, it returns the number of units that can be purchased (what is display in the `Max (x)` on your screenshots). Apparently, it doesn't work as expected when the cost includes a decimal place.

This test reproduce the issue:

```javascript
expect(getGeometricMaxBuyable({
    start: 4,  // you have 4 occultists
    available: 85,  // you have 85 minions
    base: 30,  // the first occultist costs 30 minions
    // occultist n costs occultist n-1 * 1.3
    increaseFactor: 1.3 
})).toEqual(1)
// currently fails by returning 0
```

Based on my tests, using this function:

- occultist 1 cost `30`
- occultist 2 costs `30 * 1.3 = 39`
- occultist 3 costs `39 * 1.3 = 50.7`
- occultist 4 costs `50.7 * 1.3 = 65.91000000000001`
- occultist 5 costs `65.91000000000001 * 1.3 = 85.68300000000002`, and since it's higher than your 85 minions, the function return 0 (you can't buy any minion) and we get the bug

I have absolutely no idea where to start to fix this :')

@ko-pp, @Chelsea486MHz any pointers?

**Comment by Chelsea486MHz** [comment]
Use the floor function to trunk down to the nearest integer

floor(85.2)=85
